### ISSUE TITLE
Please use more descriptive commits

### ISSUE THREAD

**Issue by Katorone** [ExileNG/NGSpaceCompany#1]
Hi !

In absence of a changelog, I like to look at the most recent commits to see what's changed.  So far they're only being described as "dev", which isn't informative.

Also, thank you for picking up this project.  I've always enjoyed playing Space Company, and appreciate the sleek new look and attention you're giving it.

**Comment by briangithex** [comment]
There _is_ a changelog.  Both in-game (click the version number in the top left) and on github ( https://github.com/ExileNG/NGSpaceCompany/releases ).

**Comment by Katorone** [comment]
Whelp, I entirely missed those.  Thanks!

**Comment by Mr-Wallet** [comment]
Wow, I had no idea! The whole reason I am here is because I've been coming to the releases to see the changelog. Maybe that version should be more... bootstrap-buttony? 🤔 

Or perhaps include the changelog in the update notification?
