### ISSUE TITLE
Bug: Remaining time until empty storage is not always populated

### ISSUE THREAD

**Issue by briangithex** [ExileNG/NGSpaceCompany#12]
Sample save: https://gist.github.com/briangithex/51059d6c2c8b9dff4fde7dbe3dae92f0

My suspicion is that the reason "Remaining time until empty storage" on the battery tab is not populated is that my current energy level exceeds my battery capacity due to Dimensional rift.  However, my energy balance is negative so it should still be populated.

**Comment by ExileNG** [comment]
Fixed in 1.20.1
