### ISSUE TITLE
Suggestion: Pinned resources

### ISSUE THREAD

**Issue by briangithex** [ExileNG/NGSpaceCompany#2]
Add a pin button next to each resource on the left sidebar.  If a resource is pinned, it would be duplicated under a category (e.g., named "pinned") at the top of the resource sidebar.  This category could be closed/opened just like any other category.

I admit that this would probably require the resource panel  to be ~50 pixels wider.

Possibly this button should be hidden behind an early game science upgrade, to avoid offering UX before the player needs it.

You could avoid polluting the resource sidebar if the pin button was in individual resource panes rather than on the sidebar.

**Comment by JakobPapirov** [comment]
Pinning a resource sounds like an great feature if the played a few resources that they want to monitor closely. In addition this could possibly reduce the amount of time spent hiding/unhiding resource panes and a bit of scrolling. 

If the possibility of saving the scroll state, as mentioned in another suggestion, is not worth the time, then this might be a compromise?

**Comment by briangithex** [comment]
Added in 1.20.  Thanks!
