### ISSUE TITLE
Suggestion: Shortcut button for EMC, to make it less obnoxious before Auto-EMC is unlocked.

### ISSUE THREAD

**Issue by eliannelavoie** [ExileNG/NGSpaceCompany#23]
From my [Reddit comment](https://www.reddit.com/r/incremental_games/comments/on82eb/what_games_are_you_playing_this_week_game/h5r4vkq/):

> I also got a bit annoyed with EMC: it's really frustrating to have to go back and forth every time you want to create a resource, you know? You notice you need to minutes of wood, you go to EMC, you click wood, you go back, you notice you still need a bit of wood, you go back to EMC, you click wood, etc...
> So I made myself a little EMC shortcut!
![image](https://i.imgur.com/7FSn9ZO.gif)
> Just making sure: is this a problem other people have? Would it be worth it to open an issue on GitHub and make a pull request?

The code is on my fork in a branch [eliannelavoie/NGSpaceCompany/tree/issues/23-emc-shortcut](https://github.com/eliannelavoie/NGSpaceCompany/tree/issues/23-emc-shortcut).

The shortcut is only shown next to Costs that aren't full.
Of course, I can understand why someone would want to disable it, so I added an option to the EMC pane and made the default value "false":
![image](https://user-images.githubusercontent.com/13744678/126387587-a526de5b-d735-4001-801f-16f8f8933b4a.png)

It displays correctly if you have Auto-EMC unlocked:
![image](https://user-images.githubusercontent.com/13744678/126387830-13f126c6-b475-4f8f-a3ee-4e54abf46910.png)

And since I'm from Québec, I also did the french translation:
![image](https://user-images.githubusercontent.com/13744678/126390748-2a070f72-6108-4bb9-a640-7b8a64c3deaa.png)

Should I open a pull request?

Thanks!

**Comment by eliannelavoie** [comment]
Oh, and also, I did my best to respect the coding/structure conventions of the project, but feel free to tell me if missed something!

**Comment by ExileNG** [comment]
added in 1.29.0
