### ISSUE TITLE
Bug: Antimatter titan is not applied to terraforming costs

### ISSUE THREAD

**Issue by Voltara** [ExileNG/NGSpaceCompany#29]
The antimatter titan is not being correctly applied to terraforming costs.  This looks like a typo in the code: the attribute is named `terraformCosts`, not `terraformerCosts`.

https://github.com/ExileNG/NGSpaceCompany/blob/e115ebe2623363666058a669c0b8cc3b2eb90332/src/store.js#L423-L426

**Comment by ExileNG** [comment]
fixed in 1.31.2
