### ISSUE TITLE
Bug: Antimatter titan applied twice to probe and terraform costs

### ISSUE THREAD

**Issue by Voltara** [ExileNG/NGSpaceCompany#30]
The antimatter titan bonus is being applied twice for probe and terraform costs.  _I suspect statue costs are also affected by this bug_, but I'm not far enough into the game to verify.  This results in a 99% cost reduction instead of 90%.  Reloading the page resets the costs to the expected, correct values.

Note how in the `computeCosts` function, `item.costs` gets reset to the base cost before applying the scaling and titan modifiers:

https://github.com/ExileNG/NGSpaceCompany/blob/f67e12d04719f252afb3963509f61291d9e48099/src/store.js#L408

This is not done for `probeCosts`, `terraformCosts`, or `statueCosts`, so the titan bonus will stack every time `computeCosts` is called for the star.

**Comment by ExileNG** [comment]
fixed in 1.31.3

**Comment by Voltara** [comment]
The change isn't working correctly.  Here's what I see in the code.

1) In `computeCosts()`, the titan discount is applied to `terraformBaseCosts` and `statueBaseCosts`.  It should be applied to `terraformCosts` and `statueCosts` instead.  (The change to probes looks OK.)

https://github.com/ExileNG/NGSpaceCompany/blob/f889a9d0e6b6c4b54807c54ead1840c8af18884a/src/store.js#L425-L437

2) In `terraform()`, it is using `terraformBaseCosts` when subtracting the resource from your supply.  It should use `terraformCosts` instead (this depends on fix 1).

https://github.com/ExileNG/NGSpaceCompany/blob/f889a9d0e6b6c4b54807c54ead1840c8af18884a/src/store.js#L2773-L2777

3) In `buildStatue()`, it is using `statueBaseCosts` when checking if the player has sufficient resource.  It should use `statueCosts` instead (this also depends on fix 1).  This might result in the player ending up with a negative resource count.

https://github.com/ExileNG/NGSpaceCompany/blob/f889a9d0e6b6c4b54807c54ead1840c8af18884a/src/store.js#L2793-L2800
