### ISSUE TITLE
Bug: Possible to build statue without having all of the required resource

### ISSUE THREAD

**Issue by Voltara** [ExileNG/NGSpaceCompany#32]
Some stars have two of the same resource, for example lunarite and lunarite.  The cost to build a statue will be listed as:

    Lunarite    100T
    Lunarite    100T

In this example, the total cost to build is 200T lunarite.  However, it is possible to build the statue while having as little as 100T lunarite in inventory.  (The player's lunarite count would go negative, but the game increases the value to zero.)

**Comment by ExileNG** [comment]
Fixed in 1.34.0
