### ISSUE TITLE
Bug: Unable to gain 0.5 Meteorites

### ISSUE THREAD

**Issue by briangithex** [ExileNG/NGSpaceCompany#5]
Combining Storage Discount and Capital Investment, it's possible to reach a state where one has partial meteorites (e.g., 199.5 meteorites).  In this scenario, Capital Investment is not awarded for having 100% Meteorite, Meteorite total in left sidebar is not green, and neither "Gain 1" nor EMC can be used to collect the final 0.5 Meteorites.  Conveniently, Storage Discount prevents this from being a soft lock.

**Comment by ExileNG** [comment]
Do you have any exported data to make test on my side ?

**Comment by briangithex** [comment]
Here's an export that demonstrates the issue: https://gist.github.com/briangithex/cdec4856b918c3ae0fe83ed0e895ba48

I crafted it manually by toggling Meteorite Generators off and manually subtracting 0.5 meteorites from my stock.  This is sufficient to reproduce the issue (i.e., both "Gain 1" and "EMC" fail to collect the final 0.5 Meteorites).

I think the normal way for this to happen during natural gameplay is for a purchase to somehow have a fractional Meteorite cost. 
 This is only really an issue for Meteorite, since Meteorite initially relies exclusively on Gain/EMC, rather than on resource generators.

**Comment by briangithex** [comment]
Paying more careful attention, the specific trigger for this bug is that the first upgrade of many resources is 50, which translates to 37.5 when multiplied by 75% via storage discount.

**Comment by ExileNG** [comment]
Fixed in 1.19.0

**Comment by briangithex** [comment]
Gain suffers from the same problem, but I'm not sure if that matters, since the only mechanical place where this bug has any impact is meteorite.
